### ISSUE TITLE
为啥存入Ether 不需要Approve？百思不得姐

### ISSUE THREAD

**Issue by andyesfly** [Linhieng/learn-dapp#1]

**Comment by Linhieng** [comment]
时间过去有点久了，我也不太确定了。

我当时好像是这样理解的：

token 的来源是从 `钱包 metamask`，最最后面实际操作的时候，你就会发现，当你想要从里面取出余额的时候，是需要批准的。
ether 是从 token 来的， 存 ether 时，不需要进过 `metamask` 了。

token  和 ether 本质是一个东西，只是概念不太同。当时的我这样理解的 ：
钱都是从 `metamask` 来的，需要先从钱包中取出前，这些钱叫做 `token`，然后还需要再将前放入 “交易所 exchange”，这些存进去的就是 `ether`。

**Comment by andyesfly** [comment]
这个视频的代码，bug好多，兄台在做web3的项目吗

**Comment by Linhieng** [comment]
没有，当时只是因为需要了解区块链，所以找到了这个视频。

这个视频太久了，我当时看一半后本来打算就不看了，但是感觉亏了，所以才继续看下去，跑到最后有个效果就行了。

如果真需要用到区块链的技术，直接自己搭建我感觉是不科学的，想要真正能用，可以去看看 百度的 [百度超级链](https://xuper.baidu.com/n/ps/opensource)
