### ISSUE TITLE
请教下作者溯源的问题

### ISSUE THREAD

**Issue by JasperHall** [Linhieng/learn-dapp#2]
你好，我也想做一个溯源的小项目，但是有点无从下手。请问作者现在完成了溯源的项目了吗？用的什么区块链啊？

**Comment by Linhieng** [comment]
后面没做了，如果你想做的话，你可以去看看[百度的超级链](https://xuper.baidu.com/)。用以太坊搭建我感觉有点麻烦。

**Comment by JasperHall** [comment]
> 后面没做了，如果你想做的话，你可以去看看[百度的超级链](https://xuper.baidu.com/)。用以太坊搭建我感觉有点麻烦。

好的谢谢
